// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9-kghSQnJObsBy0tOLHY5dv6cae2hGaU',
    appId: '1:651515565301:android:97ea950e2231abca68e1bc',
    messagingSenderId: '651515565301',
    projectId: 'fytlyf-staging-test',
    storageBucket: 'fytlyf-staging-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNU1m45CL0B7455xTGRHYuiytaLZPJizo',
    appId: '1:651515565301:ios:18d891e81e5f182668e1bc',
    messagingSenderId: '651515565301',
    projectId: 'fytlyf-staging-test',
    storageBucket: 'fytlyf-staging-test.firebasestorage.app',
    androidClientId: '651515565301-qjm6uq2n3517q8pil1k0b19pr1kg6utl.apps.googleusercontent.com',
    iosClientId: '651515565301-1ib60k7d6tk378ib9551s1qitfua30n3.apps.googleusercontent.com',
    iosBundleId: 'com.fytlyf.appt',
  );
}
