// Auto-generated by Gemini Agent — reviewed for FytLyf 2025 structure
import 'package:flutter/material.dart';

class AppColors {
  static const Color primary = Colors.red;
  static const Color secondary = Colors.black;
  static const Color white = Colors.white;
}
