// Auto-generated by Gemini Agent — reviewed for FytLyf 2025 structure
import 'package:flutter/material.dart';

class AppTextStyles {
  static const TextStyle h1 = TextStyle(
    fontSize: 24,
    fontWeight: FontWeight.bold,
  );
  static const TextStyle body = TextStyle(
    fontSize: 16,
  );
}
