// Auto-generated by Gemini Agent — reviewed for FytLyf 2025 structure

class AppValidators {
  static String? email(String? value) {
    if (value == null || value.isEmpty) {
      return 'Please enter an email';
    }
    return null;
  }
}
