// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTO-Qo0y_4jlgcXEvxsAvTlwd_URJqS5M',
    appId: '1:431911773857:android:63c9238dea48ee2f49f2e0',
    messagingSenderId: '431911773857',
    projectId: 'fytlyf-production-realtime',
    storageBucket: 'fytlyf-production-realtime.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEIqpTcdmNb2iQSPyEW7jv-hWOGW5V9_Q',
    appId: '1:431911773857:ios:d4ba022caf1a02af49f2e0',
    messagingSenderId: '431911773857',
    projectId: 'fytlyf-production-realtime',
    storageBucket: 'fytlyf-production-realtime.firebasestorage.app',
    iosClientId: '431911773857-26rq66a5pq1ee98dnuiq22b1i1fepqs8.apps.googleusercontent.com',
    iosBundleId: 'com.fytlyf.fytlyf',
  );
}
