// Auto-generated by Gemini Agent — reviewed for FytLyf 2025 structure
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class AdaptiveTextField extends StatelessWidget {
  const AdaptiveTextField({super.key});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    if (theme.platform == TargetPlatform.iOS) {
      return const CupertinoTextField();
    } else {
      return const TextField();
    }
  }
}
